### ISSUE TITLE
First byte timeout in varnish cache when changing username

### ISSUE THREAD

**Issue by twhite96** [thepracticaldev/DEV-ios#132] opened 2019-03-05 00:10 UTC
**Describe the bug**
Varnish cache first byte timeout error when changing username

**To Reproduce**
1. Go to profile
2. Click on username
3. Type new username
4. Press submit
5. 503 first bytes timeout Guru Mediation

**Expected behavior**
Expected to change my username after hitting submit

**Screenshots**

![image](https://user-images.githubusercontent.com/7698292/53771735-ca8ecb00-3eb1-11e9-9ed3-8d430b1e0de4.gif)

**Smartphone (please complete the following information):**
 - Device: iPad Pro 12.9" latest
 - OS: iOS 12.1.4

**Additional context**

**Comment by StriderHND** [comment] 2019-03-06 16:47
Hello @twhite96 

I'm trying to reproduce de issue, but is updating the username correctly

**Comment by twhite96** [comment] 2019-03-06 22:37
I'll try this on my Mac. Not sure what is happening. Even turned off my VPN.

**Comment by twhite96** [comment] 2019-03-06 22:40
Happening on my Mac as well.

**Comment by chickdan** [comment] 2019-03-07 19:35
The 503 is an HTTP status code, making it is a server side issue. This should be moved to https://github.com/thepracticaldev/dev.to

**Comment by twhite96** [comment] 2019-03-07 19:48
>The 503 is an HTTP status code, making it is a server side issue. This should be moved to https://github.com/thepracticaldev/dev.to

@chickdan yeah I did. It's in the main repo

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jessleenyc** [comment] 2019-04-22 19:13
Closing this issue since it's been represented here: https://github.com/thepracticaldev/dev.to/issues/1994

**Closed by jessleenyc** 2019-04-22 19:13 UTC
Labels: triage
