### ISSUE TITLE
User profile tab occasionally timesout/freezes

### ISSUE THREAD

**Issue by benhalpern** [thepracticaldev/DEV-ios#42] opened 2018-10-09 16:34 UTC
In using the app, I find that sometimes the user profile tab causes issues where the loading icon changes and nothing seems to help until the app is refreshed.

I imagine this has to do with the logic that we use to gather the relevant user info to display.

**Comment by chickdan** [comment] 2018-10-09 20:55
Hmm, I haven't had any issues and I've been using the app at least a few times a day. Is it freezing when you navigate to the profile tab or as soon as you open the app?

**Comment by jessleenyc** [comment] 2018-10-29 21:36
Closing this for now since we can't reproduce.

**Closed by jessleenyc** 2018-10-29 21:36 UTC
